---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: facebooc
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/lfs269/facebooc-deploy.git

